name: Performance Tests
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Chromium
        run: sudo apt-get install chromium-browser
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install
        run: npm install
      - name: Run Performance tests
        if: always()
        run: npm run test:performance
      